from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
from datetime import datetime
import os

class ExportService:
    @staticmethod
    def generate_pdf_report(topology, performance, output_path):
        doc = SimpleDocTemplate(output_path, pagesize=A4)
        styles = getSampleStyleSheet()
        
        # Custom styles
        title_style = ParagraphStyle(
            'TitleStyle',
            parent=styles['Heading1'],
            fontSize=18,
            textColor=colors.HexColor("#58a6ff"),
            alignment=1,
            spaceAfter=20
        )
        
        elements = []
        
        # Header
        elements.append(Paragraph("Industrial Network Simulation Report", title_style))
        elements.append(Paragraph(f"Generated on: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", styles['Normal']))
        elements.append(Spacer(1, 20))
        
        # Summary Section
        elements.append(Paragraph("Network Performance Summary", styles['Heading2']))
        if performance:
            avg_latency = sum(p['latency_ms'] for p in performance if p['latency_ms'] > 0) / len([p for p in performance if p['latency_ms'] > 0])
            max_latency = max(p['latency_ms'] for p in performance)
            elements.append(Paragraph(f"Average Latency: {avg_latency:.3f} ms", styles['Normal']))
            elements.append(Paragraph(f"Maximum Latency: {max_latency:.3f} ms", styles['Normal']))
        else:
            elements.append(Paragraph("No performance data available.", styles['Normal']))
        
        elements.append(Spacer(1, 20))
        
        # Device Table
        elements.append(Paragraph("Connected Devices", styles['Heading2']))
        
        data = [["ID", "Tipo", "Protocolo", "Estado", "Latencia (ms)"]]
        for node in topology['nodes']:
            # Find performance for this node
            perf = next((p for p in performance if p['id'] == node['id']), None)
            latency = f"{perf['latency_ms']}" if perf and perf['latency_ms'] > 0 else "N/A"
            
            # Clean up potentially Enum-style strings
            dev_type = str(node['type']).split('.')[-1]
            protocol = str(node['protocol']).split('.')[-1]
            status = str(node['status']).split('.')[-1]

            data.append([
                node['display_name'] or node['id'],
                dev_type,
                protocol,
                status,
                latency
            ])
            
        table = Table(data, colWidths=[120, 70, 110, 80, 80])
        table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#161b22")),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 12),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('BACKGROUND', (0, 1), (-1, -1), colors.HexColor("#faffff")), # Lighter white for background
            ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#d0d7de")),
            ('FONTSIZE', (0, 1), (-1, -1), 10),
            ('TOPPADDING', (0, 1), (-1, -1), 8),
            ('BOTTOMPADDING', (0, 1), (-1, -1), 8),
        ]))
        
        elements.append(table)
        elements.append(Spacer(1, 40))
        
        # Methodology Footer
        footer_style = ParagraphStyle('FooterStyle', parent=styles['Normal'], fontSize=8, textColor=colors.grey)
        elements.append(Paragraph("Automated report generated by NetSim Industrial Engine. All values calculated based on simulated protocol overhead and jitter models.", footer_style))
        
        doc.build(elements)
        return output_path
